server:
  port: 8762
spring:
  application:
    name: eureka-server-bravo
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      default-zone: http://eureka-server-alpha.com:8761/eureka, http://eureka-server-charlie.com:8763/eureka
  server:
    # 自我保护机制 关闭
    enable-self-preservation: false
  instance:
    hostname: eureka-server-bravo.com