server:
  port: 8763
spring:
  application:
    name: eureka-server-charlie
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      # 此处必须使用camelCase 如果使用under_score_case会导致Eureka集群互相注册失败
      defaultZone: http://eureka-server-alpha.com:8761/eureka, http://eureka-server-bravo.com:8762/eureka
  server:
    # 自我保护机制 关闭
    enable-self-preservation: false
  instance:
    hostname: eureka-server-charlie.com